OCPBUGS-1153: Add etcd operator roles and clusterrole
openshift/cluster-etcd-operator pull request #1020
Opened 2023-03-07 10:51 UTC by tjungblu

cc @Elbehery

2023-03-07 12:41 UTC, tjungblu commented
a little further than before, it's still not picking up the right permissions though:

> W0307 11:35:56.170919       1 builder.go:230] unable to get owner reference (falling back to namespace): pods "etcd-operator-8dd67b5f-fgg98" is forbidden: User "system:serviceaccount:openshift-etcd-operator:etcd-operator" cannot get resource "pods" in API group "" in the namespace "openshift-etcd-operator"


> I0307 11:35:56.718457       1 server.go:93] Error checking for connectivity to apiserver (GET lease openshift-etcd-operator/openshift-cluster-etcd-operator-lock): leases.coordination.k8s.io "openshift-cluster-etcd-operator-lock" is forbidden: User "system:serviceaccount:openshift-etcd-operator:etcd-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-etcd-operator"

which are both included in the cluster role and in the operator namespace role :/

2023-03-09 08:30 UTC, stlaz requested changes

2023-03-09 08:30 UTC, stlaz commented on manifests/0000_20_etcd-operator_04_clusterrolebinding.yaml
> -  name: system:openshift:operator:etcd-operator
that name was correct

2023-03-09 08:30 UTC, stlaz commented on manifests/0000_20_etcd-operator_04_clusterrole.yaml
> +  name: etcd-operator-cluster-role
`system:openshift:etcd-operator-cluster-role`

2023-03-09 11:18 UTC, tjungblu commented
/test e2e-operator

2023-03-09 13:56 UTC, tjungblu commented
/test e2e-operator

2023-03-09 17:22 UTC, Elbehery commented
well done @tjungblu  💯 👍🏽

2023-03-09 19:54 UTC, Elbehery commented
/retest-required

2023-04-06 09:37 UTC, Elbehery commented
@tjungblu shall we close this, as we `wont do` ?

2023-04-11 07:50 UTC, tjungblu commented
yep

/close

2023-04-11 07:50 UTC, closed without merging